heat_template_version: 2018-03-02

description: Template that creates a private network

parameters:
  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.
    default: public
  cidr:
    type: string
    label: Network CIDR
    description: The CIDR of the private network.
    default: '192.168.100.0/24'
  dns:
    type: comma_delimited_list
    label: DNS nameservers
    description: Comma separated list of DNS nameservers for the private network.
    default: '8.8.8.8'

resources:
  private_network:
    type: OS::Neutron::Net
  
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_network }
      cidr: { get_param: cidr }
      dns_nameservers: { get_param: dns } 

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_network }

  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet: { get_resource: private_subnet }

  
  my_instance_ubuntu:
    type: OS::Nova::Server
    properties:
      image: Ubuntu 16.04
      flavor: cy.medium
      name: baseLinux
      networks: [network: {get_resource: private_network}]
      user_data: |
        #!/bin/bash
        echo "ubuntu:abc123!@#" | chpasswd
        sudo sed 's/PasswordAuthentication no/PasswordAuthentication yes/' </etc/ssh/sshd_config >~/sshd_config && sudo mv ~/sshd_config /etc/ssh/sshd_config
        sudo service ssh restart
      user_data_format: RAW
      
  my_instance3:
    type: OS::Nova::Server
    properties:
      image: Ubuntu 16.04
      flavor: cy.medium
      name: metasploitLinux
      networks: [network: {get_resource: private_network}]
      user_data: |
        #!/bin/bash
        echo "ubuntu:abc123!@#" | chpasswd
        sudo sed 's/PasswordAuthentication no/PasswordAuthentication yes/' </etc/ssh/sshd_config >~/sshd_config && sudo mv ~/sshd_config /etc/ssh/sshd_config
        sudo service ssh restart
        curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall
      user_data_format: RAW
